[package]
name = "pf2e"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Léo Jetzer"]
license = "MIT"
description = "A template to create Pathfinder 2nd Edition homebrew content"

repository = "https://github.com/Hayen03/pf2e_template"
keywords = ["pathfinder"]
categories = ["visualization"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"